sudo: required
language: python
python: 2.7
env:
  global:
  - MULLED_NAMESPACE=jmchiltonorg
  - secure: IEQm28UDNUjMKQmmEA6DptG0RE2+9eaXoLHim5LOnLi/zNSTvOUhCrK9zXfH6jR79c50Mtir7JMMeC53SOCnJFcoItz/yGshDB1A/W+O/LCVG9vmxmd7MPNnt+NOOP2CQg4661TreA+nJfJ2Eau1sgdHTKthXmAmdbqW4+IH4jiSkO2fkk+9coyJifgVTTfBkQ74fTAwbBdFNsML/nFriL4H82qSlyzC0sWLKy5DGN7nWsCtjGez3t1ABTwSM+JksCrDcE4p9dQFh5FvDCehN88CvR3yN7xZr+FOH/OhFfnuYmKouXc6uDj5yd4t703lbhJVgQHNDrD3hhjA5POlYJv+prUTRGFx/HF2m+7yyTxEeP9yqfuqOeNCmUk7MmmHc4zeT/rWn0qMV2gMWd6noYtbULvwQEez/f+mlqqKM5uiManRoLlK/gLbpHdOD9zxSuom4xiyQczvo3u5B6CD/8iddC216hfswi1CaELeya7zBceJPRWS5KBVeApstZbsljvIDKdesTGkCNW431RRRrjGeP0d8LGTNXt2Sjg9clYBFdvbiqwcNuSD5R2ttOmeLic7eWYarNGGub80R1CQLR2pNyoezbnXPhcBudL9pMMtBIvJNGHJrZMXMJr4iYO/mZoe0ew1xxfjh9JDYumthqbEfX2VIF1iZVJF63m3wI4=
  - secure: LASKXjmFlLUipYLlg0CcK3AbXxq4YYve+k3c7lXB2z6ixpn2/2juq0c4faEiFwM0Opt2GyAp91S8l3/Fbu2r4yKTagv9H3id/nB5iFNmLDYf3Hv0zStrmw2T/sUw4AbgDnkpzCJ6ey/rrF81turxDRbRdMprbYryL3I+8CsWU1YzH1LIv0No8CuB/jQh2tFz456Rmwb84WK5rC/zP8Bvd7z5lvnHuc/qKLiMLjmMepIjx+yF61N3d7p7SQR/5OvW7OHUfBd5QEybMdoe5XnMi+1VvmFl4P7GIqivOTiNiqb+sZv/SXFRKeaM1QoRTYjuYyJQI/bTBIWvAmoVqMpy5pFGzAAoD4GhfPJfDcVTxRhO6B0t0b3PccfXnc+ZgHF+WO7bjI/ub0k+G2ed7g3B9nc09QdSkyKyoYrV8ce/T1UpRPyVd6OhhxmrPcHGG87FvxMikAlnHWXFBWHgwL1TFY5O92uWqY1EaIVHVd8tkXOBqPNa/2/D90jIMgsuw7IKiTSuEtPwfIWCjyh9Rs34U6kOvXZcT3xfseB8XdYz08Ogt4oTMt028hsJA96H8LKx/ezxDO5ZI96Ge0j/y0W6CvnatEwxFtkaBBwpw0vtVaMh6Aimey5wqMCn698gdzToINHOJq87xOccG3JSOTnO+MhxWQQlh6aTQP2jjSFkH2s=
  - secure: hfMqkWrskhAxvXsbLB0oL+oziY1S7nVDgLhR0YkvsEwXlNNOLinErw9KuQkSNjXpM7zkICWiwS9Q5eigKkIbNxbXo3vjdLh5CNqIUT05ynR3AhpCA8TbE7v0Jpq2fT44T5vb5/aP2g8aUmMslGFtvgbAEf8bhPImV03XBP6sF1u5g3gGwetDJ+pQufV79E60JiLYpGSq8rmmcChQfmdZkA/IxTtRkv97qfpTr6JpNyrCxhPMd3jXjrA8uTGsY0v6/SnhkGd5PKsjgOim874G63MlBg8WFXOxlsD3YkkJKsYbcwHC14m3sXU5ewvyyVD/wI1N1JrNqG2/YnL2cA+sCn5/LQ0GNGQJze2kMSGwmCbbPR1SPJxbplh0VhMoBMXcaWrCNaInye81GU+KWdWwA2SRQ70RgsWCh+wWvYF+B7s0jFcTT6gDWVh8XG5W31f1VcRer+zxhe4Kzvyr8zhx3uWhfQeJJ4656gnFQ99nHoGZbRfLB5Rro/PSrm4dVcTHwsKjBWO2xqnUACEzTA96/6UVfGQ3oQeWiyzcVEsht7v0U1FETW3ze8WdFzb16pdkJGeel2O7zmBwjjStST88akVJH9zmMTz6XXVZXeh2M79mo/82ppUDoUKKAZMhTawOCetFfr1XLMB4WiTVK0i0SiXLlPigh5eo3QnnBULNxIo=
services:
- docker
before_install:
- pip install requests
- pip install galaxy-lib
- sudo apt-get update -qq
- sudo apt-get install docker-engine --no-install-recommends -y -o Dpkg::Options::="--force-confmiss"
  -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew"
- sudo apt-get install sshpass --no-install-recommends -y
- docker --version
- docker info
script:
- mulled-build-files --check-published --singularity --namespace $MULLED_NAMESPACE build-and-test ./combinations
after_success:
- |
  if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then
     mulled-build-files --check-published --namespace $MULLED_NAMESPACE --oauth-token $QUAY_OAUTH_TOKEN push ./combinations;
     ls;
     ls singularity_import;
     [ "$(ls -A singularity_import)" ] && echo 'uploading Singularity images' && sshpass -p "$SSH_PASSWORD" scp -v singularity_import/mull* ubuntu@192.52.2.34:/home/ubuntu/singularity/
  fi
